### PR TITLE
Add 5.2 rulseset

### PR DESCRIPTION
**Pull request by DevShep**
Fixes https://github.com/yola/yophpcs/issues/6

Ping @beck

### CODE REVIEW

**Comment by beck** [comment]
is there any way to make the side-effects ignore more specific?

I think the rule a good and useful. It would be idea if we could keep it, but modify it to ignore usage of `require` and `require_once`

If not, this works as-is.

**Comment by DevShep** [comment]
> I think the rule a good and useful. It would be idea if we could keep it, but modify it to ignore usage of require and require_once

There is a way. We'd need to modify [this] to be more specific. The question is whether it's worth figuring out how to do--it may be simple, but it might not be. I'll take a closer look later to see if it's an easy change, but if not, I think it might be better to either ignore the rule, or tolerate it--it **is** only a warning.

**Comment by beck** [comment]
> The question is whether it's worth figuring out how to do--it may be simple, but it might not be

If simple, cool.  If not, no worries.

**Comment by DevShep** [comment]
Turned out to be simple. I wrote a unit test to check that the Sniff was ignoring the `require*`. Unfortunately, the Sniff doesn't output different text for different violations (the line number is even the same), so the test doesn't check for valid violations. I don't think it's worth hacking the test/sniff further to see if the other violations were preserved. Feel free to disagree.

**Comment by beck** [comment]
Testing locally, seems to work as intended.

I do not agree with keeping two style guides.  Lets merge this with `Yola`, maintain only one, and update the rules as our platform evolves.

**Comment by beck** [comment]
Side question:

When I do a `phpcs --config-set` do you have any clue where these settings file lives?  (I'd like to configure this file to sync across my machines)

**Comment by DevShep** [comment]
> I do not agree with keeping two style guides. Lets maintain only Yola, remove Yola52, and update the rules as the platform evolves.

Why's that? I'd rather have two rulesets to keep the 5.2 yuck separate, and Yola52 is derived from Yola, so its not like maintenance is an issue.

**Comment by DevShep** [comment]
> When I do a phpcs --config-set do you have any clue where the settings file lives? (I'd like to configure this file to sync across my machines)

I don't :(

**Comment by beck** [comment]
> I'd rather have two rulesets

If you prefer to have two, then there should be:

* The one everyone should use (including sntich)
* Varients

In this case that would be:

* `Yola`
* `Yola55`

Our style guide will only be useful if we can apply it to our current codebase.  To do so, we must start with loose guidelines, the so called "5.2 yuck", and then tighten the rules as the code becomes more tidy.

**Comment by DevShep** [comment]
@beck I moved everything into the Yola standard.

**Comment by beck** [comment]
:+1:

**Pull request merged**
